services:
  flask:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app_flask
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: app_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql